name: Rust Cargo Publish

on:
    release:
        types: [published]

env:
    CARGO_TERM_COLOR: always

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        environment: Release

        steps:
            - uses: actions/checkout@v3
            - name: Build example actix
              run: cargo build -p example-actix-basic
            - name: Build example axum
              run: cargo build -p example-axum-basic
            - name: Build example axum sqlite
              run: cargo build -p example-axum-sqlite

            - name: Create credential file
              run: |
                  touch ~/.cargo/credentials.toml
                  echo "[registry]" >> ~/.cargo/credentials.toml
                  echo "token = '${{ secrets.CARGO_KEY }}'" >> ~/.cargo/credentials.toml
            - name: Deploy to cargo
              run: cargo publish -p firebase-auth
