name: Rust

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Build example actix
              run: cargo build -p example-actix-basic
            - name: Build example axum
              run: cargo build -p example-axum-basic
            - name: Build example axum sqlite
              run: cargo build -p example-axum-sqlite
